version: "3.7"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: junglebook
      POSTGRES_USER: baloo
      POSTGRES_DB: lenslocked
    ports:
      - 5432:5432
    networks:
      - lenslocked-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - lenslocked-network

networks:
  lenslocked-network:
    driver: bridge
